# Generated by Django 3.2.7 on 2022-01-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Signatory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signatory',
            name='area',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
