# Generated by Django 3.2.7 on 2021-09-25 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=25)),
                ('designation', models.CharField(max_length=45, null=True)),
                ('user', models.CharField(max_length=45, null=True)),
                ('up', models.CharField(max_length=145, null=True)),
                ('userid', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, related_name='userarea', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_user_area',
            },
        ),
    ]
