# Generated by Django 3.2.7 on 2021-09-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_alter_userarea_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userarea',
            name='up',
            field=models.CharField(max_length=145, null=True),
        ),
        migrations.AlterField(
            model_name='userarea',
            name='user',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
