# Generated by Django 3.2.7 on 2021-09-25 04:45

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acquisition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transactiondate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('rrnumber', models.CharField(db_index=True, max_length=145)),
                ('units', models.IntegerField(default=0)),
                ('area', models.PositiveSmallIntegerField(default=0)),
                ('userid', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'acquisition',
            },
        ),
        migrations.CreateModel(
            name='brands',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(db_index=True, max_length=145)),
            ],
            options={
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='suppliers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('suppliername', models.CharField(max_length=145)),
                ('address', models.CharField(max_length=145, null=True)),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='meters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('metertype', models.CharField(max_length=145, null=True)),
                ('ampheres', models.CharField(max_length=45, null=True)),
                ('serialnos', models.CharField(max_length=145, null=True)),
                ('units', models.IntegerField(default=0)),
                ('acquisitionid', models.ForeignKey(db_column='acquisitionid', on_delete=django.db.models.deletion.PROTECT, to='Meters.acquisition')),
                ('brandid', models.ForeignKey(db_column='brandid', on_delete=django.db.models.deletion.PROTECT, to='Meters.brands')),
            ],
            options={
                'db_table': 'meters',
            },
        ),
        migrations.CreateModel(
            name='meterdetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serialno', models.CharField(max_length=45)),
                ('accuracy', models.CharField(max_length=45, null=True)),
                ('wms_status', models.PositiveSmallIntegerField(default=0, null=True)),
                ('status', models.PositiveSmallIntegerField(default=0, null=True)),
                ('active', models.PositiveSmallIntegerField(default=0, null=True)),
                ('meterid', models.ForeignKey(db_column='meterid', on_delete=django.db.models.deletion.CASCADE, to='Meters.meters')),
            ],
            options={
                'db_table': 'meterdetails',
            },
        ),
        migrations.CreateModel(
            name='meterassigned',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assigneddate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('datepaid', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('accountno', models.CharField(max_length=145)),
                ('ornumber', models.CharField(max_length=145)),
                ('coname', models.CharField(max_length=145, null=True)),
                ('coaddress', models.CharField(max_length=145, null=True)),
                ('type', models.PositiveSmallIntegerField(default=0, null=True)),
                ('active', models.PositiveSmallIntegerField(default=0, null=True)),
                ('userid', models.CharField(max_length=45)),
                ('meterdetailsid', models.ForeignKey(db_column='meterdetailsid', on_delete=django.db.models.deletion.PROTECT, to='Meters.meterdetails')),
            ],
            options={
                'db_table': 'meterassigned',
            },
        ),
        migrations.CreateModel(
            name='calibration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('testdate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('gen_average', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fullload_average', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fl1', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fl2', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fl3', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('lightload_average', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ll1', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ll2', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ll3', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reading', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('type', models.PositiveSmallIntegerField(default=0, null=True)),
                ('volts', models.CharField(max_length=45)),
                ('phase', models.CharField(max_length=45)),
                ('kh', models.CharField(max_length=45)),
                ('ta', models.CharField(max_length=45)),
                ('remarks', models.CharField(max_length=245)),
                ('active', models.PositiveSmallIntegerField(default=0, null=True)),
                ('isdamage', models.BooleanField(default=False)),
                ('userid', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meterdetailsid', models.ForeignKey(db_column='meterdetailsid', on_delete=django.db.models.deletion.PROTECT, to='Meters.meterdetails')),
            ],
            options={
                'db_table': 'calibration',
            },
        ),
        migrations.AddField(
            model_name='acquisition',
            name='supplierid',
            field=models.ForeignKey(db_column='supplierid', on_delete=django.db.models.deletion.PROTECT, to='Meters.suppliers'),
        ),
    ]
