# Generated by Django 3.2.7 on 2021-11-14 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meters', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='meterassigned',
            new_name='assigned_meter',
        ),
        migrations.AlterModelTable(
            name='assigned_meter',
            table='assigned_meter',
        ),
    ]
