# Generated by Django 3.2.7 on 2021-11-26 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Meters', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='meterseal',
        #     name='metertestid',
        # ),
        migrations.AddField(
            model_name='meterseal',
            name='meterdetailsid',
            field=models.ForeignKey(db_column='meterdetailsid', on_delete=django.db.models.deletion.PROTECT, to='Meters.meterdetails'),
            preserve_default=False,
        ),
    ]
