# Generated by Django 3.2.7 on 2021-09-25 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Meters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acquisition',
            name='supplierid',
            field=models.ForeignKey(db_column='supplierid', on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='Meters.suppliers'),
        ),
    ]
