# Generated by Django 3.2.7 on 2022-01-10 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Meters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meters',
            name='acquisitionid',
            field=models.ForeignKey(db_column='acquisitionid', on_delete=django.db.models.deletion.CASCADE, to='Meters.acquisition'),
        ),
    ]
