# Generated by Django 3.2.7 on 2021-09-20 01:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Meters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='meterassigned',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assigneddate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('datepaid', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('accountno', models.CharField(max_length=145)),
                ('ornumber', models.CharField(max_length=145)),
                ('coname', models.CharField(max_length=145, null=True)),
                ('coaddress', models.CharField(max_length=145, null=True)),
                ('type', models.PositiveSmallIntegerField(default=0, null=True)),
                ('active', models.PositiveSmallIntegerField(default=0, null=True)),
                ('userid', models.CharField(max_length=45)),
                ('idmeterdetails', models.ForeignKey(db_column='idmeterdetails', on_delete=django.db.models.deletion.CASCADE, to='Meters.meterdetails')),
            ],
            options={
                'db_table': 'meterassigned',
            },
        ),
    ]
