# Generated by Django 3.2.7 on 2021-11-14 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meters', '0002_auto_20211114_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigned_meter',
            name='transactiondate',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
