# Generated by Django 3.2.7 on 2021-09-25 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Meters', '0002_alter_acquisition_supplierid'),
    ]

    operations = [
        migrations.CreateModel(
            name='mtype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('metertype', models.CharField(db_index=True, max_length=45)),
            ],
            options={
                'db_table': 'metertype',
            },
        ),
        migrations.RemoveField(
            model_name='meters',
            name='metertype',
        ),
        migrations.AlterField(
            model_name='brands',
            name='brand',
            field=models.CharField(db_index=True, max_length=45),
        ),
        migrations.AddField(
            model_name='meters',
            name='mtypeid',
            field=models.ForeignKey(db_column='mtypeid', default=1, on_delete=django.db.models.deletion.PROTECT, to='Meters.mtype'),
            preserve_default=False,
        ),
    ]
