# Generated by Django 3.2.7 on 2022-01-10 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Meters', '0002_alter_meters_acquisitionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterseal',
            name='meterdetailsid',
            field=models.ForeignKey(db_column='meterdetailsid', on_delete=django.db.models.deletion.CASCADE, to='Meters.meterdetails'),
        ),
    ]
