# Generated by Django 3.2.7 on 2021-09-24 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Meters', '0002_meterassigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meterdetails',
            name='ampheres',
        ),
        migrations.AddField(
            model_name='meters',
            name='ampheres',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='meterdetails',
            name='idmeters',
            field=models.ForeignKey(db_column='idmeters', on_delete=django.db.models.deletion.CASCADE, to='Meters.meters'),
        ),
    ]
