# Generated by Django 3.2.7 on 2021-09-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meters', '0003_auto_20210924_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='meters',
            name='supplierid',
            field=models.IntegerField(default=None),
        ),
    ]
