# Generated by Django 3.2.7 on 2021-09-25 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meters', '0003_auto_20210925_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acquisition',
            name='units',
        ),
    ]
