# Generated by Django 3.2.7 on 2021-11-15 23:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Meters', '0003_assigned_meter_transactiondate'),
    ]

    operations = [
        migrations.CreateModel(
            name='meterseal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sealdate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('seal_a', models.CharField(max_length=45, null=True)),
                ('seal_b', models.CharField(max_length=45, null=True)),
                ('metercondition', models.PositiveSmallIntegerField(default=0, null=True)),
                ('accuracy', models.IntegerField(default=0)),
                ('reading', models.IntegerField(default=0)),
                ('remarks', models.CharField(max_length=245)),
                ('active', models.PositiveSmallIntegerField(default=0, null=True)),
                ('userid', models.CharField(max_length=45)),
                ('meterdetailsid', models.ForeignKey(db_column='meterdetailsid', on_delete=django.db.models.deletion.PROTECT, to='Meters.meterdetails')),
            ],
            options={
                'db_table': 'meterseal',
            },
        ),
    ]
