# Generated by Django 3.2.7 on 2021-11-16 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meters', '0004_meterseal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meterseal',
            old_name='sealdate',
            new_name='transactiondate',
        ),
    ]
