# Generated by Django 3.2.7 on 2022-01-25 06:13

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('Meters', '0004_auto_20220120_1229'),
    ]

    operations = [
    ]
