# Generated by Django 3.2.7 on 2021-09-28 00:54

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Meters', '0004_remove_acquisition_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='metertest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('testdate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('gen_average', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fullload_average', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('lightload_average', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fl1', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fl2', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('fl3', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ll1', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ll2', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ll3', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reading', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('type', models.PositiveSmallIntegerField(default=0, null=True)),
                ('volts', models.CharField(max_length=45)),
                ('phase', models.CharField(max_length=45)),
                ('kh', models.CharField(max_length=45)),
                ('ta', models.CharField(max_length=45)),
                ('remarks', models.CharField(max_length=245)),
                ('active', models.PositiveSmallIntegerField(default=0, null=True)),
                ('isdamage', models.BooleanField(default=False)),
                ('userid', models.IntegerField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meterdetailsid', models.ForeignKey(db_column='meterdetailsid', on_delete=django.db.models.deletion.CASCADE, to='Meters.meterdetails')),
            ],
            options={
                'db_table': 'metertest',
            },
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='userid',
            field=models.IntegerField(max_length=45),
        ),
        migrations.DeleteModel(
            name='calibration',
        ),
    ]
