# Generated by Django 3.2.7 on 2022-01-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meters', '0005_auto_20220125_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterdetails',
            name='is_read',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
