# Generated by Django 3.2.7 on 2021-09-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meters', '0005_auto_20210928_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition',
            name='acqtype',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='acquisition',
            name='userid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='metertest',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
