# Generated by Django 3.2.7 on 2022-01-21 02:26

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('Meters', '0006_meterdetails_rtw_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterdetails',
            name='rtw_at',
            field=models.DateTimeField(null=sqlalchemy.sql.expression.true),
        ),
    ]
