# Generated by Django 3.2.7 on 2022-01-28 03:43

from django.db import migrations, models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('Meters', '0006_meterdetails_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterdetails',
            name='info',
            field=models.TextField(null=sqlalchemy.sql.expression.true),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
        migrations.AddField(
            model_name='meterdetails',
            name='rtw_at',
            field=models.DateTimeField(null=sqlalchemy.sql.expression.true),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
        migrations.AddField(
            model_name='meterdetails',
            name='updated_at',
            field=models.DateTimeField(null=sqlalchemy.sql.expression.true),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
        migrations.AlterField(
            model_name='meterdetails',
            name='serialno',
            field=models.CharField(db_index=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='sealdetails',
            name='serialno',
            field=models.CharField(db_index=True, max_length=45),
        ),
    ]
