# Generated by Django 3.2.7 on 2021-10-12 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Meters', '0006_auto_20210930_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='seals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('boxes', models.IntegerField(default=0)),
                ('ppb', models.IntegerField(default=0)),
                ('serialnos', models.CharField(max_length=45, null=True)),
                ('acquisitionid', models.ForeignKey(db_column='acquisitionid', on_delete=django.db.models.deletion.PROTECT, to='Meters.acquisition')),
                ('brandid', models.ForeignKey(db_column='brandid', on_delete=django.db.models.deletion.PROTECT, to='Meters.brands')),
            ],
            options={
                'db_table': 'seals',
            },
        ),
    ]
