# Generated by Django 3.2.7 on 2021-10-12 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Meters', '0007_seals'),
    ]

    operations = [
        migrations.CreateModel(
            name='sealdetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serialno', models.CharField(max_length=45)),
                ('techcrew', models.CharField(max_length=45, null=True)),
                ('status', models.PositiveSmallIntegerField(default=0, null=True)),
                ('active', models.PositiveSmallIntegerField(default=0, null=True)),
                ('meterdetailsid', models.ForeignKey(db_column='meterdetailsid', on_delete=django.db.models.deletion.PROTECT, to='Meters.meterdetails')),
                ('sealid', models.ForeignKey(db_column='sealid', on_delete=django.db.models.deletion.CASCADE, to='Meters.seals')),
            ],
            options={
                'db_table': 'sealdetails',
            },
        ),
    ]
