# Generated by Django 3.2.7 on 2021-11-04 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meters', '0009_alter_sealdetails_meterdetailsid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meterassigned',
            old_name='coaddress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='meterassigned',
            old_name='coname',
            new_name='consumer',
        ),
        migrations.RemoveField(
            model_name='meterassigned',
            name='accountno',
        ),
        migrations.RemoveField(
            model_name='meterassigned',
            name='assigneddate',
        ),
        migrations.RemoveField(
            model_name='meterassigned',
            name='datepaid',
        ),
        migrations.RemoveField(
            model_name='meterassigned',
            name='ornumber',
        ),
    ]
