# Generated by Django 3.2.7 on 2021-11-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meters', '0010_auto_20211104_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterassigned',
            name='type',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
