# Generated by Django 3.2.7 on 2021-11-05 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Meters', '0011_alter_meterassigned_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterassigned',
            name='metertestid',
            field=models.ForeignKey(db_column='metertestid', default=1, on_delete=django.db.models.deletion.PROTECT, to='Meters.metertest'),
            preserve_default=False,
        ),
    ]
